- name: Configurar VM para deploy da aplicação e monitoramento
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Aguardar conexão SSH estar disponível
      ansible.builtin.wait_for_connection:
        delay: 15
        timeout: 300

    - name: Atualizar cache do apt e pacotes do sistema
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    - name: Instalar pacotes essenciais
      ansible.builtin.apt:
        name:
          - curl
          - gnupg
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Criar diretório para configuração do Prometheus
      ansible.builtin.file:
        path: "/opt/monitoring"
        state: directory
        mode: '0755'

    - name: Renderizar template do Prometheus para a VM
      ansible.builtin.template:
        src: prometheus.yml.j2
        dest: /opt/monitoring/prometheus.yml
        mode: '0644'