- name: Configurar VM para deploy da aplicação e monitoramento
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Aguardar conexão SSH estar disponível
      ansible.builtin.wait_for_connection:
        delay: 15
        timeout: 300

    - name: Atualizar cache do apt e instalar pacotes para Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: present
        update_cache: yes

    - name: Adicionar chave GPG oficial do Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: yes

    - name: Adicionar usuário ao grupo docker
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Criar diretório da aplicação
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Renderizar template do Docker Compose para a VM
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2
        dest: "{{ app_dir }}/docker-compose.yml"
        mode: '0644'
        
    - name: Iniciar (ou recriar) os contêineres da aplicação
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        state: present 
        recreate: 'always'  