name: Build, Provision, and Deploy to GKE

on:
  push:
    branches: [ main, development ]

env:
  GCP_ZONE: southamerica-east1-b
  TERRAFORM_DIR: ./terraform-k8s/
  GKE_CLUSTER_BASE_NAME: todo-ua 
  IMAGE_REPO_BACK: todolist-ua-back
  IMAGE_REPO_FRONT: todolist-ua-front

jobs:
  deploy:
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'stage' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Environment Name
      id: get_env
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "ENV_NAME=production" >> $GITHUB_OUTPUT
        else
          echo "ENV_NAME=stage" >> $GITHUB_OUTPUT
        fi

    - name: Authenticate to GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK & Kubectl
      uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: gke-gcloud-auth-plugin

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
        ENV_NAME=${{ steps.get_env.outputs.ENV_NAME  }}
        TF_BUCKET="tf-state-${{ secrets.GCP_PROJECT_ID }}"
        echo "Using Terraform state bucket: gs://${TF_BUCKET}"
        gcloud storage buckets describe gs://${TF_BUCKET} >/dev/null 2>&1 || gcloud storage buckets create gs://${TF_BUCKET} --project=${{ secrets.GCP_PROJECT_ID }} --location=southamerica-east1 --uniform-bucket-level-access
        terraform init \
          -backend-config="bucket=${TF_BUCKET}" \
          -backend-config="prefix=terraform/state/$ENV_NAME"
      working-directory: ${{ env.TERRAFORM_DIR }}

    - name: Terraform Plan
      run: |
        terraform plan -no-color -out=tfplan \
          -var="gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="gcp_zone=${{ env.GCP_ZONE }}" \
          -var="environment=${{ steps.get_env.outputs.ENV_NAME }}"
      working-directory: ${{ env.TERRAFORM_DIR }}

    - name: Terraform Apply
      run: terraform apply -auto-approve -no-color tfplan
      working-directory: ${{ env.TERRAFORM_DIR }}
    
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_BASE_NAME }}-${{ steps.get_env.outputs.ENV_NAME }} \
          --zone ${{ env.GCP_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Install/Upgrade Monitoring Stack
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh > /dev/null 2>&1

        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update

        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
          --namespace monitoring --create-namespace \
          --set grafana.service.type=LoadBalancer \
          --set grafana.adminUser=admin \
          --set grafana.adminPassword=admin123 \
          --set grafana.defaultDashboardsEnabled=true \
          --set prometheus.service.type=ClusterIP \
          --wait

    - name: Install/Upgrade Loki Stack
      run: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

        helm upgrade --install loki grafana/loki-stack \
          --namespace monitoring --create-namespace \
          --set grafana.enabled=false \
          --set promtail.enabled=true \
          --set loki.persistence.enabled=true \
          --set loki.persistence.size=10Gi \
          --set loki.persistence.storageClassName=standard \
          --wait
    
    - name: Configure Docker
      run: gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet 

    - name: Build & Push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/todolist-backend-repo-${{ steps.get_env.outputs.ENV_NAME }}/${{ env.IMAGE_REPO_BACK }}:${{ github.sha }}

    - name: Build & Push Frontend
      uses: docker/build-push-action@v4
      with:
        context: . 
        file: ./Dockerfile 
        push: true
        tags: southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/todolist-frontend-repo-${{ steps.get_env.outputs.ENV_NAME }}/${{ env.IMAGE_REPO_FRONT }}:${{ github.sha }}
   
    - name: Prepare Manifest File
      run: |
        ENV_NAME=${{ steps.get_env.outputs.ENV_NAME }}
        BACK_IMAGE_URL="southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/todolist-backend-repo-$ENV_NAME/${{ env.IMAGE_REPO_BACK }}:${{ github.sha }}"
        FRONT_IMAGE_URL="southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/todolist-frontend-repo-$ENV_NAME/${{ env.IMAGE_REPO_FRONT }}:${{ github.sha }}"
        cp infra/$ENV_NAME.yaml manifest.temp.yaml
        sed -i "s|IMAGE_BACKEND_PLACEHOLDER|$BACK_IMAGE_URL|g" manifest.temp.yaml
        sed -i "s|IMAGE_FRONTEND_PLACEHOLDER|$FRONT_IMAGE_URL|g" manifest.temp.yaml

    - name: Deploy all resources from Manifest
      run: kubectl apply -f manifest.temp.yaml

    - name: Verify deployments
      run: |
        ENV_NAME=${{ steps.get_env.outputs.ENV_NAME }}
        kubectl rollout status deployment/backend -n $ENV_NAME --timeout=3m
        kubectl rollout status deployment/frontend -n $ENV_NAME --timeout=3m
